workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          flutter packages get
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/**/*.ipa
    publishing:
      email:
        recipients:
          - 74331334+AspireRB@users.noreply.github.comtu-email@example.com